<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array<int, string>
     */
    protected $except = [
			/* '/api/v1/js_error',
			'/api/v1/auth',
			'/api/v1/check_password_change',
			'/api/v1/recovery_pass',
			'/api/v1/upload_photo',
			'/api/v1/update_email',
			'/api/v1/upload_file_for_manager',
			'/api/v1/post_mess_for_manager',
			'/api/v1/add_new_employee',
			'/api/v1/edit_employee',
			'/api/v1/notification_delegation',
			'/api/v1/get_all_news',
			'/api/v1/get_news',
			'/api/v1/mark_all_news_as_read',
			'/api/v1/get_delivery_addresses',
			'/api/v1/add_new_delivery_addresses',
			'/api/v1/edit_delivery_addresses',
			'/api/v1/delete_delivery_addresses',
			'/api/v1/get_other_data',
			'/api/v1/add_new_counterparty',
			'/api/v1/weight_calculation',
			'/api/v1/order_creation',
			'/api/v1/delete_transport',
			'/api/v1/get_transport',
			'/api/v1/add_new_transport',
			'/api/v1/download_price_list',
			'/api/v1/order_confirm',
			'/api/v1/get_leftover_metal_for_products',
			'/api/v1/get_product_balances',
			'/api/v1/upload_file_for_non_standard_addition',
			'/api/v1/delete_counterparty',
			'/api/v1/get_employees',
			'/api/v1/edit_transport',
			'/api/v1/logout',
			'/api/v1/mark_all_notification_as_read',
			'/api/v1/mark_notification_as_read',
			'/api/v1/get_all_orders',
			'/api/v1/get_all_notifications',
			'/api/v1/get_order_details',
			'/api/v1/order_cancel',
			'/api/v1/get_metal_presence_report',
			'/api/v1/delete_draft',
			'/api/v1/download_order_details',
			'/api/v1/get_all_orders_for_shipment',
			'/api/v1/shipment_creation',
			'/api/v1/get_other_variables',
			'/api/v1/delete_file_for_non_standard_addition',
			'/api/v1/download_invoice',
			'/api/v1/download_mutual_settlements',
			'/api/v1/delete_file_for_manager',
			'/api/v1/get_draft_details',
			'/api/v1/commercial_offers_edit_or_creation',
			'/api/v1/get_draft_for_new_commercial_offer',
			'/api/v1/get_old_commercial_offer',
			'/api/v1/delete_commercial_offer',
			'/api/v1/download_commercial_offer',
			'/api/v1/order_creation2',
			'/api/v1/get_invoices',
			'/api/v1/download_list_of_invoices',
			'/api/v1/get_shipping_warehouses',
			'/api/v1/get_all_shipments',
			'/api/v1/get_product_remains',
			'/api/v1/download_product_remains',
			'/api/v1/get_substandard',
			'/api/v1/download_substandard',
			'/api/v1/get_finished_products',
			'/api/v1/download_finished_products',
			'/api/v1/add_news',
			'/api/v1/add_to_cart',
			'/api/v1/get_shipping_details',
			'/api/v1/delete_from_cart',
			'/api/v1/edit_quantity_from_cart',
			'/api/v1/get_cart',
			'/api/v1/get_cart_info',
			'/api/v1/length_check',
			'/api/v1/save_non_standard_addition',
			'/api/v1/get_product_availability',
			'/api/v1/download_draft_details',
			'/api/v1/copy_order',
			'/api/v1/clear_cart' */
    ];
}
