export const errors: Map<string, string> = new Map<string, string>([
  //Работа с файлами
  ['INCORRECT_UPLOADING', 'Некорректная загрузка'],
  ['INCORRECT_EXPANSION', 'Некорректное расширение файла'],
  ['LIMIT_FILE_SIZE', 'Превышен допустимый размер файла'],
  ['NULL_FILE_SIZE', 'Нулевой размер файла'],
  ['FAIL_UPLOAD_FILE', 'Не удалось загрузить файл, возможно проблема с доступом к папке'],
  //Загрузка аватара
  ['INCORRECT_UPLOADING', 'Некорректная загрузка'],
  ['NO_VALID_IMAGE', 'Вероятно, изображение некорректное, возможно повреждено'],
  // Добавление/редактирование сотрудника
  ['LIMIT_EMPLOYEES', 'Превышен лимит по количеству сотрудников'],
  ['MISSING_NUMBER_CHARACTERS_FOR_PASSWORD', 'Пароль должен содержать цифры'],
  ['MISSING_LOWER_CASE_CHARACTERS_FOR_PASSWORD', 'Пароль должен содержать заглавные буквы'],
  ['MISSING_UPPER_CASE_CHARACTERS_FOR_PASSWORD', 'пароль должен содержать строчные буквы'],
  ['PASSWORD_MUST_HAVE_AT_LEAST_8_CHARACTERS', 'Длина пароля должна превышать 8 символов'],
  ['PASS1_NOT_EQUAL_PASS2', 'Введенные пароли не совпадают'],
  //Добавление адреса доставки
  ['CITY_IS_EMPTY_OR_INCORRECT', 'Город не указан либо заполнен некорректно'],
  ['INDEX_IS_EMPTY_OR_INCORRECT', 'Индекс не указан либо заполнен некорректно'],
  ['STREET_IS_EMPTY_OR_INCORRECT', 'Улица не указана либо заполнена некорректно'],
  ['REGION_IS_EMPTY_OR_INCORRECT', 'Регион не указан либо заполнен некорректно'],
  ['FIO_IS_INCORRECT', 'Некорректный формат ФИО контактного лица'],
  ['ID_DELIVERY_ADDRESSES_IS_EMPTY_OR_INCORRECT', 'Адрес доставки не указан либо заполнен некорректно'],
  //"Добавление сотрудника"
  ['FIO_IS_EMPTY_OR_INCORRECT', 'Фамилия или имя или отчестве пустое либо заполнено некорректно'],
  ['FIO_IS_INCORRECT', 'Фамилия или имя или отчестве некорректно, все поля должны быть заполнены'],
  ['LAST_NAME_FIRST_NAME_AND_PATRONYMIC_FIELDS_MUST_BE_FILLED_IN', 'Поля фамилия, имя и отчестве должны быть заполнены'],
  ['PHONE_IS_EMPTY_OR_INCORRECT', 'Телефон пуст или некорректно заполнен'],
  ['FAIL_PHONE', 'Телефон некорректен'],
  ['EMAIL_IS_EMPTY_OR_INCORRECT', 'Email пуст или некорректно заполнен'],
  ['FAIL_EMAIL', 'Email некорректен'],
  ['NO_EXISTS_EMPLOYEE_ACCOUNT', 'Аккаунт пользователя не найден'],
  ['NO_EXISTS_EMPLOYEE_DELEGATE_ACCOUNT', 'Аккаунт пользователя которому делегируются уведомления не найден'],
  ['PASS_IS_EMPTY_OR_INCORRECT', 'Пароль пуст или некорректно заполнен'],
  ['Пользователь с таким логином уже существует', 'Пользователь с таким логином уже существует'],
  ['THE_PHONE_NUMBER_ALREADY_EXISTS_IN_THE_DATABASE', 'Пользователь с таким номером телефона уже существует'],
  //Редактирование сотрудника
  ['FIO_IS_EMPTY_OR_INCORRECT', 'Фамилия или имя или отчестве пустое либо заполнено некорректно'],
  ['FIO_IS_INCORRECT', 'Фамилия или имя или отчестве некорректно, все поля должны быть заполнены'],
  ['LAST_NAME_FIRST_NAME_AND_PATRONYMIC_FIELDS_MUST_BE_FILLED_IN', 'Поля фамилия, имя и отчестве должны быть заполнены'],
  ['PHONE_IS_EMPTY_OR_INCORRECT', 'Телефон пуст или некорректно заполнен'],
  ['FAIL_PHONE', 'Телефон некорректен'],
  ['EMAIL_IS_EMPTY_OR_INCORRECT', 'Email не заполнен или некорректно заполнен'],
  ['FAIL_EMAIL', 'Email некорректен'],
  ['NO_EXISTS_EMPLOYEE_ACCOUNT', 'Аккаунт пользователя не найден'],
  ['NO_EXISTS_EMPLOYEE_DELEGATE_ACCOUNT', 'Аккаунт пользователя? которому делегируются уведомления не найден'],
  // "Создание заказа" и "Сохранение заказа в черновик"
  ['FIELD_LENGTH_MUST_BE_A_NUMBER', 'Длина должна быть числом'],
  ['THIS_COUNTERPARTY_IS_NOT_CONFIRMED', 'Данный контрагент не подтвержден'],
  ['NO_EXISTS_COUNTERPARTY_ID', 'Некорректный ID контрагента'],
  ['NO_EXISTS_SHIPPING_WAREHOUSE_ID', 'Некорректный ID склада'],
  ['FIELD_LENGTH_MUST_BE_GREATER_THAN_ZERO', 'Длина должна быть больше нуля'],
  ['FIELD_LENGTH_MUST_CONTAIN_THE_VALUE', 'Длина должна содержать какое то значение'],
  ['FIELD_LENGTH_HAS_AN_INCORRECT_VALUE', 'Длина имеет не корректное значение'],
  ['FIELD_QUANTITY_MUST_BE_A_NUMBER', 'Количество должно быть числом'],
  ['THE_QUANTITY_FIELD_MUST_CONTAIN_AN_INTEGER', 'Количество должно быть целым числом'],
  ['FIELD_QUANTITY_MUST_BE_GREATER_THAN_ZERO', 'Количество должно быть больше нуля'],
  ['FIELD_DESCRIPTION_MUST_BE_FILLED_IN', 'Описание должно быть указано'],
  ['THE_QUANTITY_OF_GOODS_IN_THE_ORDER_MUST_BE_GREATER_THAN_ZERO', 'Количество товаров в заказе должно быть больше нуля'],
  ['COUNTERPARTY_NOT_SPECIFIED', 'Контрагент не указан'],
  ['SHIPPING_WAREHOUSE_NOT_SPECIFIED', 'Склад не указан'],
  ['DELIVERY_ADDRESS_NOT_SPECIFIED', 'Адрес доставки не указан'],
  ['LIMIT_MAX_COUNT_GOODS', 'Превышено максимальное количество товаров в заказе'],
  ['LIMIT_MAX_COUNT_GOODS_NON_STANDARD_ADDITION', 'Превышено максимальное количество нестандартных элементов'],
  ['LIMIT_MAX_COUNT_PHOTOS_NON_STANDARD_ADDITION', 'Превышено максимальное количество фотографий нестандартных элементов'],
  ['LIMIT_MAX_COUNT_FILES_NON_STANDARD_ADDITION', 'Превышено максимальное количество файлов нестандартных элементов'],
  ['FIELD_LENGTH_MUST_BE_A_NUMBER', 'Длина должна быть числом'],
  ['THIS_COUNTERPARTY_IS_NOT_CONFIRMED', 'Данный контрагент не подтвержден'],
  ['NO_EXISTS_COUNTERPARTY_ID', 'Некорректный ID контрагента'],
  ['NO_EXISTS_SHIPPING_WAREHOUSE_ID', 'Некорректный ID склада'],
  ['THE_QUANTITY_OF_GOODS_IN_THE_ORDER_MUST_BE_GREATER_THAN_ZERO', 'Количество товаров в заказе должно быть больше нуля'],
  ['DELIVERY_DATE_NOT_SPECIFIED', 'Дата доставки не указана'],
  ['NOT_FOUND_DRAFT', 'Черновик не найден'],
  //"Скачивание деталей заказа
  ['NO_ORDERS_FOUND', 'Заказ не найден'],
//Делегирование уведомлений
  ['NO_AVAILABLE_EMPLOYEES_IN_THE_DATABASE', 'В базе данных нет доступных сотрудников'],
//Подтверждаем заказ
  ['NO_ORDERS_FOUND', 'Заказ не найден'],
//Отправка кода подтверждения при смене почты
  ['CODE_IS_EMPTY_OR_INCORRECT', 'Код подтверждения пуст или не корректен'],

//Добавление транспортного средства или Редактирование транспортного средства
  ['BRAND_IS_EMPTY_OR_INCORRECT', 'Марка транспортного средства пуста или не корректна'],
  ['LICENSE_PLATE_IS_EMPTY_OR_INCORRECT', 'Гос. номер пуст или не корректен'],
  //Делегирование уведомлений
  [`YOU_CAN'T_DO_THIS_REQUEST`, 'У Вас нет прав для выполнения данного запроса'],
  //Делегирование уведомлений
  [`PHONE_IS_EMPTY_OR_INCORRECT`, 'Телефон пуст или некорректен'],
  [`FAIL_PHONE`, 'Неверный формат номера'],
  [`PASSWORD_MUST_HAVE_AT_LEAST_8_CHARACTERS`, 'Пароль должен содержать не менее 8 символов'],
  [`MISSING_UPPER_CASE_CHARACTERS_FOR_PASSWORD`, 'Пропущена заглавная буква'],
  [`MISSING_LOWER_CASE_CHARACTERS_FOR_PASSWORD`, 'Пропущена строчная буква'],
  [`MISSING_NUMBER_CHARACTERS_FOR_PASSWORD`, 'Пропущена цифра'],
  [`BANNED`, 'Вы временно заблокированы'],
  [`WRONG_PASSWORD`, 'Неверный пароль'],
  [`Пользователь заблокирован`, 'Пользователь заблокирован'],
  [`Основной пользователь заблокирован`, 'Основной пользователь заблокирован'],
  //"Смена почты"
  ['FAIL_EMAIL', 'Некорректная почта'],
  ['FAIL_POST_EMAIL', 'Не удалось отправить email. Пожалуйста, повторите попытку позже'],
  //"Отправка кода подтверждения при смене почты"
  ['FAIL_CODE', 'Неправильный код подтверждения'],
  ['THE_CODE_IS_NOT_CORRECT', 'Неверный код подтверждения'],
  ['THE_VERIFICATION_CODE_HAS_EXPIRED', 'Время жизни кода подтверждения истекло'],
  ['CODE_IS_EMPTY_OR_INCORRECT', 'Код подтверждения пуст или не корректен'],
  //Создание коммерческого предложения
  ['RECIPIENT_OF_THE_COMMERCIAL_OFFER_IS_NOT_FILLED_IN', '“Получатель коммерческого предложения” это поле ввода не заполнено'],
  ['FIELD_ITS_OWN_PRICE_MUST_BE_A_NUMBER', 'Поле ввода “своя цена” должно содержать число'],
  ['FIELD_ITS_OWN_PRICE_MUST_NOT_BE_LESS_THAN_ZERO', 'Поле ввода “своя цена” должно содержать число больше нуля'],
  ['FIELD_ITS_OWN_PRICE_SHOULD_NOT_BE_MORE_THAN_1_BILLION', 'Поле ввода “своя цена” не должно содержать число больше 1 миллиарда'],
  ['NO_DRAFT_FOUND', 'Черновик не найден'],
  ['NO_FOUND_COMMERCIAL_OFFER', 'Коммерческое предложение не найдено'],
  ['MARKUP_PERCENTAGE_IS_EMPTY_OR_INCORRECT', 'Поле ввода “Процент наценки” пустое или некорректно заполнено'],
  //Отправка черновика менеджеру без изменения черновика
  ['THIS_COUNTERPARTY_IS_NOT_CONFIRMED', 'Контрагент не подтвержден'],
  ['NO_EXISTS_COUNTERPARTY_ID', 'Некорректный ID контрагента'],
  ['NO_EXISTS_SHIPPING_WAREHOUSE_ID', 'Некорректный ID склада'],
  //Накладные
  ['THIS_COUNTERPARTY_IS_NOT_CONFIRMED', 'Данный контрагент не подтвержден'],
  ['NO_EXISTS_COUNTERPARTY_ID', 'Некорректный ID контрагента'],
  ['NO_EXISTS_SHIPPING_WAREHOUSE_ID', 'Некорректный ID склада'],
  // Загрузка фото элемента нестандартной доборки
  ['INCORRECT_UPLOADING', 'Некорректная загрузка'],
  ['NO_VALID_IMAGE', 'Вероятно изображение некорректное, возможно повреждено'],
  ['NO_VALID_FILE', 'Вероятно этот файл не является изображением'],
  ['INCORRECT_EXPANSION', "Некорректное расширение файла, поддерживаются только jpg, png, jpeg, gif, xls, xlsx, doc, rar, zip, 7z форматы"],
  ['LIMIT_FILE_SIZE', 'Превышен максимальный размер файла'],
  ['NULL_FILE_SIZE', 'Нулевой размер файла'],
  ['FAIL_UPLOAD_IMAGE', 'Не удалось загрузить изображение, возможно'],
  // Добавление новости
  ['THE_INPUT_FIELD_SUBJECT_IS_NOT_FILLED_IN', 'Поле ввода “Тема” не заполнено'],
  ['THE_INPUT_FIELD_TEXT_IS_NOT_FILLED_IN', 'Поле ввода “Текст” не заполнено'],
  ['THE_INPUT_FIELD_HEADER_IS_NOT_FILLED_IN', 'Поле ввода “Тема” не заполнено'],
  //Добавление товара в корзину
  ['QUANTITY_MUST_BE_A_NUMBER', 'Количество должно быть числом'],
  ['QUANTITY_MUST_CONTAIN_AN_INTEGER', 'Количество должно быть целым числом'],
  ['QUANTITY_MUST_BE_GREATER_THAN_ZERO', 'Количество должно быть больше нуля'],
  ['QUANTITY_SHOULD_NOT_BE_MORE_THAN_1_BILLION', 'Количество не должно быть больше 1 миллиарда'],
  ['QUANTITY_IS_TOO_BIG', 'Количество слишком большое'],
  ['POSITION_NOT_FOUND', 'Позиция не найдена'],
  ['THIS_PRODUCT_HAS_ALREADY_BEEN_ADDED_TO_THE_CART_PREVIOUSLY', 'Этот продукт уже добавлен в корзину'],
  // Проверка корректности длины
  ['FIELD_LENGTH_MUST_BE_A_NUMBER', 'Длина должна быть числом'],
  ['FIELD_LENGTH_MUST_BE_GREATER_THAN_ZERO', 'Длина должна быть больше нуля'],
  ['FIELD_LENGTH_MUST_CONTAIN_THE_VALUE', 'Длина должна содержать какое то значение'],
  ['FIELD_LENGTH_HAS_AN_INCORRECT_VALUE', 'Длина имеет некорректное значение'],
  // Восстановление пароля
  ['PHONE_IS_EMPTY_OR_INCORRECT', 'Телефон пустой или некорректно заполнен'],
  ['FAIL_PHONE', 'Ошибочный номер телефона'],
  ['FIO_IS_EMPTY_OR_INCORRECT', 'ФИО пустые или некорректно заполнены'],
  ['NO_EXISTS_ACCOUNT', 'Несуществующий аккаунт'],
  ['FIO_IS_INCORRECT', 'Некорректные ФИО'],
  ['FIO_DOES_NOT_MATCH_PHONE_NUMBER', 'ФИО не совпадает с номером телефона'],
  // Авторизация
  ['Пользователь заблокирован', 'Вы заблокированы'],
  ['Пользователь не найден', 'Пользователь не найден'],
  ['Основной пользователь заблокирован', 'Вы а так же основной пользователь заблокированы'],
  ['FAIL_VEHICLE_TYPE', 'Некорректный тип транспорта'],
  ['', ''],
  // Создание отгрузки
  ['LIMIT_MAX_COUNT_ORDERS', 'Превышено максимальное количество заказов'],
  ['TRANSPORT_NOT_SPECIFIED', 'Транспорт не указан'],
  ['DELIVERY_ADDRESS_IS_NOT_FILLED_IN', 'Адрес доставки не заполнен'],
  ['NO_ESTIMATED_SHIPPING_TIME_SPECIFIED', 'Не указано время доставки'],
  ['NO_ORDERS_FOUND', 'Заказ не найден'],
  ['FAIL_DELIVERY_SHIPPING_DATE', 'Некорректная дата доставки'],
  ['COUNT_ARRAY_ORDERS_IS_ZERO', 'Количество заказов должно быть больше нуля'],
  ['THESE_SHIPMENTS_HAVE_ALREADY_BEEN_CREATED_PREVIOUSLY', 'Эти отгрузки уже были созданы ранее'],
  //Отправляем сообщение менеджеру
  ['NO_EXISTS_ATACH', 'Вложение не найдено'],
  ['SUBJECT_IS_EMPTY_OR_INCORRECT', 'Тема пустая или некорректно заполнена'],
  ['MESS_IS_EMPTY_OR_INCORRECT', 'Сообщение пустое или некорректно заполнено'],
  //Корзина
  ['CART_IS_EMPTY', 'Корзина пустая'],
  //
  ['ID_IS_EMPTY_OR_INCORRECT', 'Идентификатор пустой или некорректно заполнен'],
  ['YOU_CANNOT_DELETE_THIS_COUNTERPARTY', 'У Вас нет прав для удаления этого контрагента'],
  ['NO_EXISTS_ID', 'Несуществующий идентификатор'],
  ['THIS_IS_THE_MAIN_COUNTERPARTY_AND_CANNOT_BE_DELETED', 'Это головной контрагент и его нельзя удалить'],
  ['', ''],
  // Скачивание прайс-листа
  ['DELIVERY_ADDRESS_NOT_SPECIFIED', 'Не указан адрес доставки'],
  ['COULD_NOT_FIND_THE_TABLE_WITH_THE_COUNTERPARTY_DATA', 'Не удалось найти таблицу с данными контрагента'],
  ['COULD_NOT_FIND_TABLE_WITH_ORDER_DATA', 'не удалось найти таблицу с данными заказов'],
  ['COULD_NOT_FIND_THE_TABLE_WITH_SHIPMENT_DATA', 'не удалось найти таблицу с данными отгрузок'],
  ['THIS_PRODUCT_IS_NOT_AVAILABLE_FOR_ORDER', 'этот товар недоступен для заказа'],
  ['IT_LOOKS_LIKE_THIS_EMPLOYEE_IS_NOT_IN_THE_DATABASE', 'Кажется, этого сотрудника нет в базе данных'],
  // ...
  ['CONNECTION_TIMEOUT', 'Время подключения истекло'],
  ['RESULT_IS_EMPTY', 'Пустой результат запроса'],
  ['FAIL_SOCKET_CONNECT', 'Неудачное подключение'],
])
